type NullableElement<T extends Element> = T | null;

const byId = <T extends HTMLElement>(id: string): NullableElement<T> =>
  document.getElementById(id) as NullableElement<T>;
const bySelector = <T extends Element>(selector: string): NullableElement<T> =>
  document.querySelector(selector) as NullableElement<T>;

export type SidePanelElements = Record<string, any>;

export const getSidePanelElements = (): SidePanelElements => ({
  // Sidebar elements
  sidebar: byId<HTMLElement>('sidebar'),
  sidebarScrim: byId<HTMLElement>('sidebarScrim'),
  openSidebarBtn: byId<HTMLButtonElement>('openSidebarBtn'),
  closeSidebarBtn: byId<HTMLButtonElement>('closeSidebarBtn'),
  rightPanel: byId<HTMLElement>('rightPanel'),
  rightPanelPanels: byId<HTMLElement>('rightPanelPanels') ?? bySelector<HTMLElement>('.right-panel-panels'),

  // Legacy references (kept for compatibility)
  settingsBtn: byId<HTMLButtonElement>('settingsBtn'),
  settingsPanel: byId<HTMLElement>('settingsPanel'),
  chatInterface: byId<HTMLElement>('chatInterface'),
  statusText: byId<HTMLElement>('statusText'),
  statusMeta: byId<HTMLElement>('statusMeta'),
  statusBar: byId<HTMLElement>('statusBar'),
  agentNav: byId<HTMLElement>('agentNav'),

  tabSelectorBtn: byId<HTMLButtonElement>('tabSelectorBtn'),
  exportBtn: byId<HTMLButtonElement>('exportBtn'),
  tabSelector: byId<HTMLElement>('tabSelector'),
  tabSelectorSummary: byId<HTMLElement>('tabSelectorSummary'),
  tabSelectorAddActive: byId<HTMLButtonElement>('tabSelectorAddActive'),
  tabSelectorClear: byId<HTMLButtonElement>('tabSelectorClear'),
  tabList: byId<HTMLElement>('tabList'),
  closeTabSelector: byId<HTMLButtonElement>('closeTabSelector'),
  selectedTabsBar: byId<HTMLElement>('selectedTabsBar'),
  sessionTabsHud: byId<HTMLElement>('sessionTabsHud'),
  sessionTabsToggle: byId<HTMLButtonElement>('sessionTabsToggle'),
  sessionTabsCount: byId<HTMLElement>('sessionTabsCount'),
  sessionTabsFavicon: byId<HTMLImageElement>('sessionTabsFavicon'),
  sessionTabsList: byId<HTMLElement>('sessionTabsList'),
  scrollToLatestBtn: byId<HTMLButtonElement>('scrollToLatestBtn'),
  newSessionFab: byId<HTMLButtonElement>('newSessionFab'),
  historyFab: byId<HTMLButtonElement>('historyFab'),
  historyDrawer: byId<HTMLElement>('historyDrawer'),
  historyDrawerScrim: byId<HTMLElement>('historyDrawerScrim'),
  historySearchInput: byId<HTMLInputElement>('historySearchInput'),
  historyDrawerItems: byId<HTMLElement>('historyDrawerItems'),
  closeHistoryDrawerBtn: byId<HTMLButtonElement>('closeHistoryDrawerBtn'),
  drawerClearHistoryBtn: byId<HTMLButtonElement>('drawerClearHistoryBtn'),
  drawerNewSessionBtn: byId<HTMLButtonElement>('drawerNewSessionBtn'),
  historyPanel: byId<HTMLElement>('historyPanel'),
  historyItems: byId<HTMLElement>('historyItems'),
  clearHistoryBtn: byId<HTMLButtonElement>('clearHistoryBtn'),
  startNewSessionBtn: byId<HTMLButtonElement>('startNewSessionBtn'),
  settingsTabSetupBtn: byId<HTMLButtonElement>('settingsTabSetupBtn'),
  settingsTabModelBtn: byId<HTMLButtonElement>('settingsTabModelBtn'),
  settingsTabBrowserBtn: byId<HTMLButtonElement>('settingsTabBrowserBtn'),
  settingsTabNetworkBtn: byId<HTMLButtonElement>('settingsTabNetworkBtn'),
  settingsTabPromptBtn: byId<HTMLButtonElement>('settingsTabPromptBtn'),
  settingsTabProfilesBtn: byId<HTMLButtonElement>('settingsTabProfilesBtn'),
  settingsTabSetup: byId<HTMLElement>('settingsTabSetup'),
  settingsTabModel: byId<HTMLElement>('settingsTabModel'),
  settingsTabBrowser: byId<HTMLElement>('settingsTabBrowser'),
  settingsTabNetwork: byId<HTMLElement>('settingsTabNetwork'),
  settingsTabPrompt: byId<HTMLElement>('settingsTabPrompt'),
  settingsTabProfiles: byId<HTMLElement>('settingsTabProfiles'),
  newProfileNameInput: byId<HTMLInputElement>('newProfileNameInput'),
  createProfileBtn: byId<HTMLButtonElement>('createProfileBtn'),
  profileEditorTitle: byId<HTMLElement>('profileEditorTitle'),
  profileEditorName: byId<HTMLInputElement>('profileEditorName'),
  profileEditorProvider: byId<HTMLSelectElement>('profileEditorProvider'),
  profileEditorApiKey: byId<HTMLInputElement>('profileEditorApiKey'),
  profileEditorModel: byId<HTMLInputElement>('profileEditorModel'),
  profileEditorEndpoint: byId<HTMLInputElement>('profileEditorEndpoint'),
  profileEditorEndpointGroup: byId<HTMLElement>('profileEditorEndpointGroup'),
  profileEditorHeaders: byId<HTMLTextAreaElement>('profileEditorHeaders'),
  profileEditorTemperature: byId<HTMLInputElement>('profileEditorTemperature'),
  profileEditorTemperatureValue: byId<HTMLElement>('profileEditorTemperatureValue'),
  profileEditorMaxTokens: byId<HTMLInputElement>('profileEditorMaxTokens'),
  profileEditorContextLimit: byId<HTMLInputElement>('profileEditorContextLimit'),
  profileEditorTimeout: byId<HTMLInputElement>('profileEditorTimeout'),
  profileEditorEnableScreenshots: byId<HTMLInputElement>('profileEditorEnableScreenshots'),
  profileEditorSendScreenshots: byId<HTMLInputElement>('profileEditorSendScreenshots'),
  profileEditorScreenshotQuality: byId<HTMLSelectElement>('profileEditorScreenshotQuality'),
  profileEditorShowThinking: byId<HTMLSelectElement>('profileEditorShowThinking'),
  profileEditorStreamResponses: byId<HTMLSelectElement>('profileEditorStreamResponses'),
  profileEditorAutoScroll: byId<HTMLSelectElement>('profileEditorAutoScroll'),
  profileEditorConfirmActions: byId<HTMLSelectElement>('profileEditorConfirmActions'),
  profileEditorSaveHistory: byId<HTMLSelectElement>('profileEditorSaveHistory'),
  profileEditorPrompt: byId<HTMLTextAreaElement>('profileEditorPrompt'),
  saveProfileBtn: byId<HTMLButtonElement>('saveProfileBtn'),
  profileJsonEditor: byId<HTMLTextAreaElement>('profileJsonEditor'),
  refreshProfileJsonBtn: byId<HTMLButtonElement>('refreshProfileJsonBtn'),
  copyProfileJsonBtn: byId<HTMLButtonElement>('copyProfileJsonBtn'),
  applyProfileJsonBtn: byId<HTMLButtonElement>('applyProfileJsonBtn'),
  permissionRead: byId<HTMLInputElement>('permissionRead'),
  permissionInteract: byId<HTMLInputElement>('permissionInteract'),
  permissionNavigate: byId<HTMLInputElement>('permissionNavigate'),
  permissionTabs: byId<HTMLInputElement>('permissionTabs'),
  permissionScreenshots: byId<HTMLInputElement>('permissionScreenshots'),
  allowedDomains: byId<HTMLTextAreaElement>('allowedDomains'),
  exportSettingsBtn: byId<HTMLButtonElement>('exportSettingsBtn'),
  importSettingsBtn: byId<HTMLButtonElement>('importSettingsBtn'),
  importSettingsInput: byId<HTMLInputElement>('importSettingsInput'),

  // Form elements - Provider & model
  provider: byId<HTMLSelectElement>('provider'),
  apiKey: byId<HTMLInputElement>('apiKey'),
  model: byId<HTMLInputElement>('model'),
  modelHint: byId<HTMLElement>('modelHint'),
  customEndpoint: byId<HTMLInputElement>('customEndpoint'),
  customEndpointGroup: byId<HTMLElement>('customEndpointGroup'),
  customHeaders: byId<HTMLTextAreaElement>('customHeaders'),
  customHeadersGroup: byId<HTMLElement>('customHeadersGroup'),

  // Form elements - Model parameters
  temperature: byId<HTMLInputElement>('temperature'),
  temperatureValue: byId<HTMLElement>('temperatureValue'),
  maxTokens: byId<HTMLInputElement>('maxTokens'),
  contextLimit: byId<HTMLInputElement>('contextLimit'),
  timeout: byId<HTMLInputElement>('timeout'),

  // Form elements - Screenshots & vision
  enableScreenshots: byId<HTMLInputElement>('enableScreenshots'),
  sendScreenshotsAsImages: byId<HTMLInputElement>('sendScreenshotsAsImages'),
  screenshotQuality: byId<HTMLSelectElement>('screenshotQuality'),
  visionBridge: byId<HTMLInputElement>('visionBridge'),
  visionProfile: byId<HTMLSelectElement>('visionProfile'),

  // Form elements - Behavior
  showThinking: byId<HTMLInputElement>('showThinking'),
  streamResponses: byId<HTMLInputElement>('streamResponses'),
  autoScroll: byId<HTMLSelectElement>('autoScroll'),
  confirmActions: byId<HTMLInputElement>('confirmActions'),
  saveHistory: byId<HTMLInputElement>('saveHistory'),

  // Form elements - Orchestrator
  orchestratorToggle: byId<HTMLInputElement>('orchestratorToggle'),
  orchestratorProfile: byId<HTMLSelectElement>('orchestratorProfile'),

  // Form elements - System prompt
  systemPrompt: byId<HTMLTextAreaElement>('systemPrompt'),
  orchestratorPromptSection: byId<HTMLElement>('orchestratorPromptSection'),
  orchestratorPromptTextarea: byId<HTMLTextAreaElement>('orchestratorPromptTextarea'),
  visionPromptSection: byId<HTMLElement>('visionPromptSection'),
  visionPromptTextarea: byId<HTMLTextAreaElement>('visionPromptTextarea'),

  // Form elements - Appearance
  uiZoom: byId<HTMLInputElement>('uiZoom'),
  uiZoomValue: byId<HTMLElement>('uiZoomValue'),
  fontPreset: byId<HTMLSelectElement>('fontPreset'),
  fontStylePreset: byId<HTMLSelectElement>('fontStylePreset'),
  themeGrid: byId<HTMLElement>('themeGrid'),

  // Settings actions
  saveSettingsBtn: byId<HTMLButtonElement>('saveSettingsBtn'),
  cancelSettingsBtn: byId<HTMLButtonElement>('cancelSettingsBtn'),

  // Profile management
  activeConfig: byId<HTMLSelectElement>('activeConfig'),
  newConfigBtn: byId<HTMLButtonElement>('newConfigBtn'),
  newProfileInput: byId<HTMLInputElement>('newProfileInput'),
  deleteConfigBtn: byId<HTMLButtonElement>('deleteConfigBtn'),
  refreshProfilesBtn: byId<HTMLButtonElement>('refreshProfilesBtn'),
  agentGrid: byId<HTMLElement>('agentGrid'),

  // Chat interface
  chatMessages: byId<HTMLElement>('chatMessages'),
  chatEmptyState: byId<HTMLElement>('chatEmptyState'),
  userInput: byId<HTMLTextAreaElement>('userInput'),
  sendBtn: byId<HTMLButtonElement>('sendBtn'),
  composer: byId<HTMLElement>('composer'),
  setupAccessBtn: byId<HTMLButtonElement>('setupAccessBtn'),
  modelSelectorWrap: byId<HTMLElement>('modelSelectorWrap'),
  modelSelect: byId<HTMLSelectElement>('modelSelect'),
  fileBtn: byId<HTMLButtonElement>('fileBtn'),
  fileInput: byId<HTMLInputElement>('fileInput'),
  zoomOutBtn: byId<HTMLButtonElement>('zoomOutBtn'),
  zoomInBtn: byId<HTMLButtonElement>('zoomInBtn'),
  zoomResetBtn: byId<HTMLButtonElement>('zoomResetBtn'),
  planDrawer: byId<HTMLElement>('planDrawer'),
  planDrawerToggle: byId<HTMLButtonElement>('planDrawerToggle'),
  planChecklist: byId<HTMLOListElement>('planChecklist'),
  planStepCount: byId<HTMLElement>('planStepCount'),
  planClearBtn: byId<HTMLButtonElement>('planClearBtn'),
  stopRunBtn: byId<HTMLButtonElement>('stopRunBtn'), // legacy, stop is now handled by sendBtn

  // Recording
  recordBtn: byId<HTMLButtonElement>('recordBtn'),
  recordingTimer: byId<HTMLElement>('recordingTimer'),
  recordedContextBadge: byId<HTMLElement>('recordedContextBadge'),
  recordedContextRemove: byId<HTMLButtonElement>('recordedContextRemove'),
  imagePickerModal: byId<HTMLElement>('imagePickerModal'),
  imagePickerGrid: byId<HTMLElement>('imagePickerGrid'),
  imagePickerCount: byId<HTMLElement>('imagePickerCount'),
  imagePickerCancel: byId<HTMLButtonElement>('imagePickerCancel'),
  imagePickerConfirm: byId<HTMLButtonElement>('imagePickerConfirm'),
  reviewTabActions: byId<HTMLButtonElement>('reviewTabActions'),
  reviewTabScreenshots: byId<HTMLButtonElement>('reviewTabScreenshots'),
  reviewActionsPanel: byId<HTMLElement>('reviewActionsPanel'),
  reviewScreenshotsPanel: byId<HTMLElement>('reviewScreenshotsPanel'),
  reviewSaveSkillBtn: byId<HTMLButtonElement>('reviewSaveSkillBtn'),
  reviewAttachOnlyBtn: byId<HTMLButtonElement>('reviewAttachOnlyBtn'),
  actionTimelineContainer: byId<HTMLElement>('actionTimelineContainer'),
});
